"""Add personal accounts, promotion, domains, hyperlink marketing and insights."""

from __future__ import annotations

from collections.abc import Sequence
import sqlalchemy as sa
from alembic import op

revision: str = "0003_business_modules"
down_revision: str | None = "0002_ip_proxy_management"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def ts() -> list[sa.Column]:
    return [sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False), sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False)]


def upgrade() -> None:
    op.create_table("personal_accounts", sa.Column("id",sa.Integer(),primary_key=True),sa.Column("public_id",sa.String(64),unique=True,nullable=False),sa.Column("name",sa.String(120),nullable=False),sa.Column("phone_e164",sa.String(20),unique=True),sa.Column("country_code",sa.String(2)),sa.Column("status",sa.String(32),nullable=False,server_default="unpaired"),sa.Column("enabled",sa.Boolean(),nullable=False,server_default=sa.true()),sa.Column("last_error",sa.Text()),sa.Column("last_connected_at",sa.DateTime(timezone=True)),sa.Column("archived_at",sa.DateTime(timezone=True)),sa.Column("created_by",sa.Integer(),sa.ForeignKey("user_accounts.id",ondelete="RESTRICT"),nullable=False),*ts())
    op.create_index("ix_personal_accounts_public_id","personal_accounts",["public_id"]);op.create_index("ix_personal_accounts_phone_e164","personal_accounts",["phone_e164"]);op.create_index("ix_personal_accounts_status","personal_accounts",["status"])
    op.create_table("message_deliveries",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("public_id",sa.String(64),unique=True,nullable=False),sa.Column("request_id",sa.String(160),unique=True,nullable=False),sa.Column("account_id",sa.Integer(),sa.ForeignKey("personal_accounts.id",ondelete="RESTRICT"),nullable=False),sa.Column("recipient_e164",sa.String(20),nullable=False),sa.Column("provider_message_id",sa.String(255),unique=True),sa.Column("status",sa.String(16),nullable=False,server_default="queued"),sa.Column("queued_at",sa.DateTime(timezone=True),nullable=False),sa.Column("sent_at",sa.DateTime(timezone=True)),sa.Column("delivered_at",sa.DateTime(timezone=True)),sa.Column("failed_at",sa.DateTime(timezone=True)),sa.Column("last_error",sa.Text()),*ts())
    op.create_index("ix_message_deliveries_request_id","message_deliveries",["request_id"]);op.create_index("ix_message_deliveries_account_id","message_deliveries",["account_id"]);op.create_index("ix_message_deliveries_status","message_deliveries",["status"])
    op.create_table("domains",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("public_id",sa.String(64),unique=True,nullable=False),sa.Column("hostname",sa.String(255),unique=True,nullable=False),sa.Column("enabled",sa.Boolean(),nullable=False,server_default=sa.true()),sa.Column("dns_status",sa.String(16),nullable=False,server_default="untested"),sa.Column("ssl_status",sa.String(16),nullable=False,server_default="untested"),sa.Column("last_verified_at",sa.DateTime(timezone=True)),sa.Column("last_error",sa.Text()),sa.Column("archived_at",sa.DateTime(timezone=True)),*ts())
    op.create_index("ix_domains_public_id","domains",["public_id"]);op.create_index("ix_domains_hostname","domains",["hostname"])
    op.create_table("promotion_templates",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("public_id",sa.String(64),unique=True,nullable=False),sa.Column("name",sa.String(120),nullable=False),sa.Column("description",sa.Text()),sa.Column("version",sa.String(40),nullable=False,server_default="1"),sa.Column("status",sa.String(16),nullable=False,server_default="active"),sa.Column("manifest_json",sa.JSON(),nullable=False),sa.Column("index_html",sa.Text(),nullable=False),sa.Column("asset_count",sa.Integer(),nullable=False,server_default="0"),sa.Column("total_size",sa.Integer(),nullable=False,server_default="0"),sa.Column("archived_at",sa.DateTime(timezone=True)),*ts())
    op.create_index("ix_promotion_templates_public_id","promotion_templates",["public_id"]);op.create_index("ix_promotion_templates_status","promotion_templates",["status"])
    op.create_table("promotion_assets",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("template_id",sa.Integer(),sa.ForeignKey("promotion_templates.id",ondelete="CASCADE"),nullable=False),sa.Column("path",sa.String(512),nullable=False),sa.Column("content_type",sa.String(120),nullable=False),sa.Column("size",sa.Integer(),nullable=False),sa.Column("content",sa.LargeBinary(),nullable=False),sa.UniqueConstraint("template_id","path",name="uq_promotion_asset_path"),*ts())
    op.create_index("ix_promotion_assets_template_id","promotion_assets",["template_id"])
    op.create_table("promotion_channels",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("public_id",sa.String(64),unique=True,nullable=False),sa.Column("channel_type",sa.String(24),nullable=False,server_default="facebook"),sa.Column("name",sa.String(120),nullable=False),sa.Column("country_code",sa.String(2),nullable=False),sa.Column("template_id",sa.Integer(),sa.ForeignKey("promotion_templates.id",ondelete="RESTRICT"),nullable=False),sa.Column("domain_id",sa.Integer(),sa.ForeignKey("domains.id",ondelete="RESTRICT")),sa.Column("slug",sa.String(120),unique=True,nullable=False),sa.Column("pixel_id",sa.Integer(),sa.ForeignKey("meta_pixels.id",ondelete="SET NULL")),sa.Column("locale_mode",sa.String(16),nullable=False,server_default="auto"),sa.Column("locale",sa.String(16)),sa.Column("status",sa.String(16),nullable=False,server_default="draft"),sa.Column("launch_at",sa.DateTime(timezone=True)),sa.Column("archived_at",sa.DateTime(timezone=True)),*ts())
    for name in ("public_id","channel_type","country_code","template_id","domain_id","slug","pixel_id","status"):op.create_index(f"ix_promotion_channels_{name}","promotion_channels",[name])
    op.create_table("promotion_events",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("public_id",sa.String(64),unique=True,nullable=False),sa.Column("channel_id",sa.Integer(),sa.ForeignKey("promotion_channels.id",ondelete="CASCADE"),nullable=False),sa.Column("event_type",sa.String(32),nullable=False),sa.Column("idempotency_key",sa.String(160),nullable=False),sa.Column("occurred_at",sa.DateTime(timezone=True),nullable=False),sa.Column("country_code",sa.String(2)),sa.Column("metadata_json",sa.JSON(),nullable=False),sa.UniqueConstraint("channel_id","idempotency_key",name="uq_promotion_event_idem"),*ts())
    op.create_index("ix_promotion_events_channel_occurred","promotion_events",["channel_id","occurred_at"]);op.create_index("ix_promotion_events_event_type","promotion_events",["event_type"])
    op.create_table("promotion_leads",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("public_id",sa.String(64),unique=True,nullable=False),sa.Column("channel_id",sa.Integer(),sa.ForeignKey("promotion_channels.id",ondelete="CASCADE"),nullable=False),sa.Column("phone_e164",sa.String(20),nullable=False),sa.Column("country_code",sa.String(2)),sa.Column("first_seen_at",sa.DateTime(timezone=True),nullable=False),sa.Column("last_seen_at",sa.DateTime(timezone=True),nullable=False),sa.Column("submission_count",sa.Integer(),nullable=False,server_default="1"),sa.UniqueConstraint("channel_id","phone_e164",name="uq_promotion_lead_phone"),*ts())
    op.create_index("ix_promotion_leads_channel_id","promotion_leads",["channel_id"]);op.create_index("ix_promotion_leads_phone_e164","promotion_leads",["phone_e164"])
    op.create_table("hyperlink_materials",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("public_id",sa.String(64),unique=True,nullable=False),sa.Column("name",sa.String(120),nullable=False),sa.Column("material_type",sa.String(24),nullable=False),sa.Column("content_json",sa.JSON(),nullable=False),sa.Column("enabled",sa.Boolean(),nullable=False,server_default=sa.true()),sa.Column("archived_at",sa.DateTime(timezone=True)),*ts())
    op.create_index("ix_hyperlink_materials_public_id","hyperlink_materials",["public_id"])
    op.create_table("hyperlink_templates",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("public_id",sa.String(64),unique=True,nullable=False),sa.Column("name",sa.String(120),nullable=False),sa.Column("content_json",sa.JSON(),nullable=False),sa.Column("material_id",sa.Integer(),sa.ForeignKey("hyperlink_materials.id",ondelete="SET NULL")),sa.Column("promotion_channel_id",sa.Integer(),sa.ForeignKey("promotion_channels.id",ondelete="SET NULL")),sa.Column("enabled",sa.Boolean(),nullable=False,server_default=sa.true()),sa.Column("archived_at",sa.DateTime(timezone=True)),*ts())
    op.create_index("ix_hyperlink_templates_public_id","hyperlink_templates",["public_id"])
    op.create_table("hyperlink_strategies",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("public_id",sa.String(64),unique=True,nullable=False),sa.Column("name",sa.String(120),nullable=False),sa.Column("max_qps",sa.Integer(),nullable=False,server_default="10"),sa.Column("concurrency",sa.Integer(),nullable=False,server_default="1"),sa.Column("batch_size",sa.Integer(),nullable=False,server_default="100"),sa.Column("retry_limit",sa.Integer(),nullable=False,server_default="1"),sa.Column("rules_json",sa.JSON(),nullable=False),sa.Column("enabled",sa.Boolean(),nullable=False,server_default=sa.true()),sa.Column("archived_at",sa.DateTime(timezone=True)),*ts())
    op.create_index("ix_hyperlink_strategies_public_id","hyperlink_strategies",["public_id"])
    op.create_table("data_packages",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("public_id",sa.String(64),unique=True,nullable=False),sa.Column("name",sa.String(120),nullable=False),sa.Column("status",sa.String(16),nullable=False,server_default="ready"),sa.Column("archived_at",sa.DateTime(timezone=True)),*ts())
    op.create_index("ix_data_packages_public_id","data_packages",["public_id"])
    op.create_table("data_package_recipients",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("public_id",sa.String(64),unique=True,nullable=False),sa.Column("data_package_id",sa.Integer(),sa.ForeignKey("data_packages.id",ondelete="CASCADE"),nullable=False),sa.Column("phone_e164",sa.String(20),nullable=False),sa.Column("country_code",sa.String(2)),sa.Column("variables_json",sa.JSON(),nullable=False),sa.UniqueConstraint("data_package_id","phone_e164",name="uq_data_package_phone"),*ts())
    op.create_index("ix_data_package_recipients_package","data_package_recipients",["data_package_id"])
    op.create_table("hyperlink_tasks",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("public_id",sa.String(64),unique=True,nullable=False),sa.Column("name",sa.String(120),nullable=False),sa.Column("template_id",sa.Integer(),sa.ForeignKey("hyperlink_templates.id",ondelete="RESTRICT"),nullable=False),sa.Column("strategy_id",sa.Integer(),sa.ForeignKey("hyperlink_strategies.id",ondelete="RESTRICT"),nullable=False),sa.Column("data_package_id",sa.Integer(),sa.ForeignKey("data_packages.id",ondelete="RESTRICT"),nullable=False),sa.Column("account_public_ids",sa.JSON(),nullable=False),sa.Column("channel",sa.String(80)),sa.Column("status",sa.String(16),nullable=False,server_default="draft"),sa.Column("total_count",sa.Integer(),nullable=False,server_default="0"),sa.Column("queued_count",sa.Integer(),nullable=False,server_default="0"),sa.Column("sent_count",sa.Integer(),nullable=False,server_default="0"),sa.Column("delivered_count",sa.Integer(),nullable=False,server_default="0"),sa.Column("failed_count",sa.Integer(),nullable=False,server_default="0"),sa.Column("started_at",sa.DateTime(timezone=True)),sa.Column("completed_at",sa.DateTime(timezone=True)),sa.Column("archived_at",sa.DateTime(timezone=True)),*ts())
    op.create_index("ix_hyperlink_tasks_public_id","hyperlink_tasks",["public_id"]);op.create_index("ix_hyperlink_tasks_status","hyperlink_tasks",["status"])
    op.create_table("hyperlink_task_deliveries",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("public_id",sa.String(64),unique=True,nullable=False),sa.Column("task_id",sa.Integer(),sa.ForeignKey("hyperlink_tasks.id",ondelete="CASCADE"),nullable=False),sa.Column("recipient_id",sa.Integer(),sa.ForeignKey("data_package_recipients.id",ondelete="RESTRICT"),nullable=False),sa.Column("account_id",sa.Integer(),sa.ForeignKey("personal_accounts.id",ondelete="SET NULL")),sa.Column("message_delivery_id",sa.Integer(),sa.ForeignKey("message_deliveries.id",ondelete="SET NULL")),sa.Column("status",sa.String(16),nullable=False,server_default="queued"),sa.UniqueConstraint("task_id","recipient_id",name="uq_task_recipient_delivery"),*ts())
    op.create_index("ix_hyperlink_task_deliveries_task","hyperlink_task_deliveries",["task_id"])
    op.create_table("ad_metrics",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("public_id",sa.String(64),unique=True,nullable=False),sa.Column("metric_date",sa.Date(),nullable=False),sa.Column("promotion_channel_id",sa.Integer(),sa.ForeignKey("promotion_channels.id",ondelete="CASCADE"),nullable=False),sa.Column("channel",sa.String(80),nullable=False),sa.Column("country_code",sa.String(2),nullable=False),sa.Column("spend",sa.Numeric(18,6),nullable=False,server_default="0"),sa.Column("impressions",sa.Integer(),nullable=False,server_default="0"),sa.Column("clicks",sa.Integer(),nullable=False,server_default="0"),sa.UniqueConstraint("metric_date","promotion_channel_id",name="uq_ad_metric_slice"),*ts())
    op.create_index("ix_ad_metrics_date_channel","ad_metrics",["metric_date","promotion_channel_id"])


def downgrade() -> None:
    for table in ("ad_metrics","hyperlink_task_deliveries","hyperlink_tasks","data_package_recipients","data_packages","hyperlink_strategies","hyperlink_templates","hyperlink_materials","promotion_leads","promotion_events","promotion_channels","promotion_assets","promotion_templates","domains","message_deliveries","personal_accounts"):
        op.drop_table(table)
